# Generated by Django 4.2.6 on 2023-10-31 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0004_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
